# all the cops that are enabled in the default
# https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml

require: rubocop-performance
require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Layout/LineLength:
  Max: 160

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 12

Metrics/AbcSize:
  Max: 20

Style/AndOr:
  Enabled: false

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  # Checks the style of children definitions at classes and modules.
  #
  # Basically there are two different styles:
  #
  # `nested` - have each child on a separate line
  #   class Foo
  #     class Bar
  #     end
  #   end
  #
  # `compact` - combine definitions as much as possible
  #   class Foo::Bar
  #   end
  #
  # The compact style is only forced, for classes / modules with one child.
  EnforcedStyle: nested
  SupportedStyles:
    - nested
    - compact
  Enabled: false

CaseIndentation:
  # Valid values are: case, end
  EnforcedStyle: case
  IndentOneStep: true

# Prefer `has_?` style for Hash methods
Style/PreferredHashMethods:
  EnforcedStyle: verbose

Rails:
  Enabled: true
